import type { Metadata } from "next";
import { Inter,Quicksand } from "next/font/google";
import "./globals.css";
import {GoogleOAuthProvider} from "@react-oauth/google"
const inter = Inter({ subsets: ["latin"] });
const quicksand = Quicksand({subsets:["latin"]});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="902232405002-kavrcv9scaobhtgufveegorqpviepq92.apps.googleusercontent.com">

      <body className={quicksand.className}>{children}</body>
      </GoogleOAuthProvider>
    </html>
  );
}
